language: node_js
node_js: '7'
cache: yarn
env:
  global:
  - PORT=3000
  - MONGODB_URI=mongodburi
  - NODE_ENV=test
  - secure: PZkuHjZwsP82WGn2rN+VWI/mlfn3qdF9/M5EAF12Puc4dcLTXZiKZVMedHwTAZiGOTMFvkt1Ti7Vks+/pplpMT90Cs5m9dbyUPqCbD/M8g0x1/YTiz8ibg8B+leNsfqTK+pt6lDA3EphbY5YgblrjP1gPFmblPMC6Sb/UrR/7pkufkUZuwBAnZj9c/oQiaG8OETzCeQLlLjPT5+JJrfWMoS7K29+GtKUkcUbdEy8XCDaEUnYwJhLkD/b3oBx5Jftoi4F3kQqFGxP6B6CN/f0VA/fHhDYeo/cz6cUYIJKEIMu8dfV+nJjyGWKsItR+gWBq7DFfTRierQ6nMxOAbhMNA9n757y+0+2RZKHtRye8cnSKeD2t1g20GoiCUvuY8Zs6ZEm+Xaz4Crq8WPJ0w40Qn7lq+HfcrW1G0IjepYFm7tL5HqwvT5DbKY/Em/xG0F1qc7uN4ddzFNo/eDVVeoetuPy3+xg2aJ75fNZd/jEWGw2BxTNcOyByQsWv4ffhdEF/UKU6gurypYGegwaDYlaGKpXVFWnXhZbhF9t1xlv18My5TcE546wLKOM7sHgTufa3R4KW36XR8larbM9XA9VTyA+64S6mtV7Na+/3Zjmd3kLReDUDLMHd6leW+bxoJHVbGFBKVRAeWd32qYdE0mNn0wQ9d4fY0fAkqXLFFX0eWI=
  - secure: lo5pHjrp7IZpMYrBQzX4xtv1vXu+KJ7uCmXm6Qau8Q+Qcz7jAl9NxmFa3RG0/f2RKPoFGIrP+qfqNBg/Ua0W3ytKikZDGN/uuPye0Ca8W+/Jubs0pTZbAsP40sacKN7XwxMrZuyzN76tSIvm+TztTeKPaC7241KOGpFoCOb+fAa+/CuFYCnA+XlsOdOe1s76oU8OOfce+G7WGy8ntI8xJ5bhCkvKKCYCKzh8+6lBAQ6Ow1yOLTai5rAlva894v2pch63XajBvUDOp7sjGr/IQAQmQAHOVL5M8P2q9O2+5wyO7KCa2OBOSVEEtPevwhGMn3LonBv2MtNnjZawAfYZbYfPS1d0ri6KBuuVUVtuCYR3ccPHkfyvu8gWSr9yx2ZISlEYbIdBOkwCbThJdT4IU9vz2Hv19SmEQq3JjkLu++p0OczEEsZ86RC1DDobLjDlrsiZbNnM7wHpWMi485pcIh524j9/ZlVis+nx482vwkjRguzCc/vInq3k+VHXugv7ZjvrPYrrSK43XoP34gxL00hRWK1XDc4K2t6V0K3dB4POxigVz9gjggK7/ciY6vCropFg0TLbubmqjPtVsJGWV2L0vjcpf8Qts7wpAVVLL/QJv3a3KCsJl8QVrEb7EJ1OTswoQCdXRmjxSFT3zS9hzOuMBf9JGDB7b4tr4xMPXUc=
branches:
  only:
  - master
addons:
  ssh_known_hosts:
  - 104.236.18.111
before_script: echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- yarn test:integration
before_deploy:
- echo -e "$DEPLOY_KEY" > /tmp/deploy_rsa
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- git remote add digitalocean $DEPLOY_REPO
deploy:
- provider: script
  skip_cleanup: true
  script: yarn deploy
after_success: yarn coverage